### PR TITLE
added Suse

### PR DESCRIPTION
**Pull request by markgraf**
Not much, but I hope it helps :-)

### CODE REVIEW

**Comment by mikegleasonjr** [comment]
Thanks for the pull request, I added a Suse box in the Vagrantfile. As soon as the tests are passing I will merge.

Thanks for contributing, don't forget to ⭐️ the repo!

**Comment by mikegleasonjr** [comment]
Hi, which version of Suse did you try.

I tried opensuse-13.2 and I get `Could not find the requested service iptables` when executing:

```
- name: Ensure iptables service is enabled & started
  service: name=iptables enabled=yes state=started
```

**Comment by markgraf** [comment]
Aaaahh!! Stupid me...

Tried SLES 11.3 and SLES 11.4. Servicename is "SuSEfirewall2"

Sorry for that :-(

**Comment by mikegleasonjr** [comment]
No worries. What about `ip6tables`?

**Comment by markgraf** [comment]
I think we can drop that one.  Apparently SuSEfirewall2 takes care of both ipv4 and ipv6.

There are two configuration options in /etc/sysconfig/SuSEfirewall2 for ipv6 though:
FW_IPv6 defaults to the ipv6 support by the Kernel when the option is empty.
FW_IPv6_REJECT_OUTGOING default configuration is yes (rejecting)

So these probably need a "lineinfile"

**Comment by markgraf** [comment]
added 2 "lineinfile"-Blocks

**Comment by mikegleasonjr** [comment]
This PR is to incomplete to be able to merge. I don't know SUSE enough to make good calls. Will close.

**Pull request closed without merging**
